Allow multiple GBT phase scan results to be written to the same file
cms-gem-daq-project/xhal pull request #113
Opened 2019-04-27 19:55 UTC by lpetre-ulb

## Description

This PR fixes https://github.com/cms-gem-daq-project/xhal/issues/111.

When the output file already exists, the function performs two sanity checks :
1. It validates the file header.
2. It ensure that the last character is EOL so that the new first line will not be merge with the previous last line.

If both checks pass, the new data are appended to the file. Therefore, it is possible to merge multiple OHs in a single result file.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

## How Has This Been Tested?

New tests have been written and pass :
``` bash
[lpetre@gem-daq reg_interface_gem]$ python -m unittest discover test
....
----------------------------------------------------------------------
Ran 4 tests in 0.019s

OK
```

Moreover the output file has been tested against the scripts from this PR : https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/201. The output plot corresponds to the generated pattern of the tests :

![canv_GBTPhaseScanResults_aa](https://user-images.githubusercontent.com/33247723/56854396-2ae03d00-6936-11e9-8282-09c697a67abe.png)

### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-04-28 10:06 UTC, bdorney commented on python/reg_interface_gem/test/data/test_saveGBTPhaseScanResults_AppendToFile.root
> +ohN/I:vfatN/I:phase/I:nRepetitions/I:nSuccesses/I
is there a reason this file is being added to the repo?

2019-04-28 10:07 UTC, bdorney commented on python/reg_interface_gem/test/data/test_saveGBTPhaseScanResults_NewFile.root
> +ohN/I:vfatN/I:phase/I:nRepetitions/I:nSuccesses/I
Same question as above.

2019-04-28 10:09 UTC, bdorney submitted a review, later dismissed

2019-04-28 15:57 UTC, lpetre-ulb commented on python/reg_interface_gem/test/data/test_saveGBTPhaseScanResults_AppendToFile.root
> +ohN/I:vfatN/I:phase/I:nRepetitions/I:nSuccesses/I
These two files have been designed (even before writing the fix for the code) to be reference files for the tests, but also to be an example for developers.

I agree with you that these files are large, but I tried to minimize as much as possible external files in the tests. For example, corrupted files are generated on-the-fly. The tests could be considered more as integration tests than unit tests since files are written.

Also, these are the files which have been tested against your PR https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/201. (But the generated file is rigorously the same.)

2019-04-30 10:50 UTC, mexanick requested changes
Please remove temporary `__init__.py`

2019-05-07 08:30 UTC, lpetre-ulb commented
I was trying to push the large objects for tests with git-lfs, but an error keeps occurring :
``` bash
[lpetre@gem-daq test]$ git push -f origin hotfix/save-gbt-phase-multiple-oh
Username for 'https://github.com': lpetre-ulb
Password for 'https://lpetre-ulb@github.com':
batch response: @lpetre-ulb can not upload new objects to public fork lpetre-ulb/xhal
error: failed to push some refs to 'https://github.com/lpetre-ulb/xhal.git'
```
It seems that either the parent repository needs to already have Git LFS object or I need write access to the parent repository as described on this [GitHub help pages](https://help.github.com/en/articles/collaboration-with-git-large-file-storage). What can I do ?

2019-05-07 12:25 UTC, lpetre-ulb commented
The two comments are addressed :
* `__init__.py` in `test/` is removed.
* Test object files are moved to Git LFS.

2019-05-07 12:36 UTC, mexanick submitted a review, later dismissed

2019-05-07 12:36 UTC, mexanick commented
please rebase on top of the current tip

2019-05-07 13:35 UTC, lpetre-ulb commented
> please rebase on top of the current tip

Rebased.

2019-05-08 07:36 UTC, jsturdy reviewed
What is the expected/desired behaviour in the event that the file being written to *already* has phase data for the given set of GBTs?

2019-05-09 07:40 UTC, bdorney commented
> What is the expected/desired behaviour in the event that the file being written to _already_ has phase data for the given set of GBTs?

Good question.  But the use case I had in mind was that this was being called for multiple OH's in an `ohMask` by the same caller (e.g. how `testConnectivity.py` is working presently).  

If we wanted to handle this case I think we should read the file in; check if the OH being written exists, if it doens't just append to the file. If it does exist then I would replace all data for this OH, leaving any other data untouched, then write a new file.  In this way it only either adds data to the file or replaces the data for one OH.

2019-05-09 07:45 UTC, bdorney commented on python/reg_interface_gem/core/gbt_utils_extended.py
> +            raise RuntimeError("The provided file ({0}) is either corrupted or not a GBT phase scan results file (no EOL before EOF).".format(filename))
I would find some other method of checking if the file is how you want it to be.  For example a user might open this file and delete the last new line either manually or due to their `vim`/`emacs` settings (e.g. remove trailing whitespace) on opening/saving/closing the file.  So this could throw an unnecessary run time error.

If you want to do this I would find some other way to accommodate this check, a "simple" check could be:

```
#END GBT Phase Scan Results
```

And since it starts with a `#` the [`TTree::ReadFile`](https://root.cern.ch/doc/master/classTTree.html#a9c8da1fbc68221b31c21e55bddf72ce7) method will ignore this line.

Although it would be harder to parse this...some thought would be necessary.

2019-05-09 07:59 UTC, jsturdy commented on python/reg_interface_gem/core/gbt_utils_extended.py
> +            raise RuntimeError("The provided file ({0}) is either corrupted or not a GBT phase scan results file (no EOL before EOF).".format(filename))
However, in your use case outlined above, is there any user interaction with this file between different OHs? (trailing whitespace won't have an effect here, only lack of newline)

2019-05-12 23:55 UTC, lpetre-ulb commented
> > What is the expected/desired behaviour in the event that the file being written to _already_ has phase data for the given set of GBTs?
> 
> Good question. But the use case I had in mind was that this was being called for multiple OH's in an `ohMask` by the same caller (e.g. how `testConnectivity.py` is working presently).
> 
> If we wanted to handle this case I think we should read the file in; check if the OH being written exists, if it doens't just append to the file. If it does exist then I would replace all data for this OH, leaving any other data untouched, then write a new file. In this way it only either adds data to the file or replaces the data for one OH.

The current behavior is to simply append data. One use case could be to increase the total number of repetitions of a GBT phase scan if the program or the user decides there is not enough statistics after the first series of scan. This would, however, require patch in the parser.

I am not sure what is the best behavior, but the current one matches the current use case. If ever, this function would need to replace the data or throw an exception, the file would need to be entirely parsed at each function call.

2019-05-13 00:04 UTC, lpetre-ulb commented on python/reg_interface_gem/core/gbt_utils_extended.py
> +            raise RuntimeError("The provided file ({0}) is either corrupted or not a GBT phase scan results file (no EOL before EOF).".format(filename))
Theses conditions have been designed as sanity checks, not bullet-proof checks. This precise condition ensures that the last character is a newline, as intended. Indeed the new data must be written to a new line a not merged with the last line of the previous data. If you or your text editor change the file in an incompatible way, the file is then considered corrupted (and it is corrupted even though it could be parsed).

2019-05-13 16:58 UTC, bdorney commented on python/reg_interface_gem/core/gbt_utils_extended.py
> +            raise RuntimeError("The provided file ({0}) is either corrupted or not a GBT phase scan results file (no EOL before EOF).".format(filename))
> However, in your use case outlined above, is there any user interaction with this file between different OHs? (trailing whitespace won't have an effect here, only lack of newline)

No within the scan and between OH's in the use case I outlined there is not.

2019-05-13 17:01 UTC, bdorney commented
> > > What is the expected/desired behaviour in the event that the file being written to _already_ has phase data for the given set of GBTs?
> > 
> > 
> > Good question. But the use case I had in mind was that this was being called for multiple OH's in an `ohMask` by the same caller (e.g. how `testConnectivity.py` is working presently).
> > If we wanted to handle this case I think we should read the file in; check if the OH being written exists, if it doens't just append to the file. If it does exist then I would replace all data for this OH, leaving any other data untouched, then write a new file. In this way it only either adds data to the file or replaces the data for one OH.
> 
> The current behavior is to simply append data. One use case could be to increase the total number of repetitions of a GBT phase scan if the program or the user decides there is not enough statistics after the first series of scan. This would, however, require patch in the parser.
> 
> I am not sure what is the best behavior, but the current one matches the current use case. If ever, this function would need to replace the data or throw an exception, the file would need to be entirely parsed at each function call.

I think for the current use case this is sufficient.  If we want to increase flexibility and try to subvert problems then the save method could take a filename as an input with the current name as the default argument.  In this way it's up to the developer whose calling the function to ensure correct usage.

Since this needs a rebase anyway...maybe @lpetre-ulb you could add that and it would then resolve this potential issue.

2019-05-14 08:40 UTC, lpetre-ulb commented
Just rebased.

2019-05-14 08:55 UTC, bdorney approved these changes

2019-05-14 09:07 UTC, bdorney commented
And approved.

2019-05-14 09:47 UTC, jsturdy approved these changes

2019-05-14 09:48 UTC, merged