Feature/ge21 compatibility
cms-gem-daq-project/xhal pull request #119
Opened 2019-06-13 09:42 UTC by mexanick

## Description

Implements GE2/1 compatibility. All new parameters are backed with default values set to GE1/1 defaults. Thus the rest of the software should be able to work unchanged. Requires cms-gem-daq-project/ctp7_modules#132 to work with GE2/1

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Need to be able to use the current legacy software for GE2/1 integration stand

## How Has This Been Tested?

Tested with GE2/1 integration stand.

### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2019-06-13 15:31 UTC, jsturdy submitted a review, later dismissed
cursory

2019-06-13 18:30 UTC, bdorney commented
Are all the commits in your development area uploaded here?

E.g. many files remain *unmodified* and I would expect some changes are needed to calibration functions, VFAT functions, optohybrid functions (broadcast read/write come immediately to mind).

Not sure if these were also updated in the ctp7_modules repo...? On my phone so it’s hard to check.

2019-06-25 09:12 UTC, bdorney commented on xhalcore/src/common/rpc_manager/daq_monitor.cc
>                  for(int vfatN = 0; vfatN < 24; ++vfatN){
`nvfats` missing here I think.

2019-06-25 09:13 UTC, bdorney commented on xhalcore/src/common/rpc_manager/vfat3.cc
> +    const uint32_t size = 12*nvfats;
do we want this `12` to be replaced with an `nohs`? I'm fine with the answer being "no".  But again this would present a potential issue for a setup driven by `GLIB`.

2019-06-25 09:18 UTC, bdorney commented
Still need some GE2/1 vs. GE1/1 fixes, e.g.:

- number of GBT's here:

https://github.com/mexanick/xhal/blob/58984c8cc70ffa03620a1388ce20fab7ba646da4/xhalcore/src/common/rpc_manager/daq_monitor.cc#L254-L261

- Number of VFATs here:

https://github.com/mexanick/xhal/blob/58984c8cc70ffa03620a1388ce20fab7ba646da4/xhalcore/src/common/rpc_manager/daq_monitor.cc#L263-L269
https://github.com/mexanick/xhal/blob/58984c8cc70ffa03620a1388ce20fab7ba646da4/xhalcore/src/common/rpc_manager/daq_monitor.cc#L458-L469

- For GE2/1 this might generate key errors?

https://github.com/mexanick/xhal/blob/58984c8cc70ffa03620a1388ce20fab7ba646da4/xhalcore/src/common/rpc_manager/daq_monitor.cc#L339-L366

Aside from these issues I think you're good; the SCA one could also be a separate issue.

2019-06-25 09:19 UTC, bdorney requested changes
Still a few places where `nvfats` or `NGBT's` is not used appropriately.

2019-06-25 09:54 UTC, jsturdy commented on xhalcore/src/common/rpc_manager/vfat3.cc
> +    for(int vfat=0; vfat < nvfats; ++vfat)
if you're changing to ensure signed/unsigned comparisons, probably you want to change here too.
also comment made [here](cms-gem-daq-project/ctp7_modules#132) re `unsigned int` vs `unsigned` vs `uintX_t`

2019-06-27 14:51 UTC, jsturdy commented
Needs `rebase` (preferably **after** addressing @bdorney's comments), and within the `rebase` preferably some cleanup of the commit history

2019-07-03 13:46 UTC, mexanick commented
I've rebased. The compatibility in the daq_monitor part deserves a separate issue in my opinion, as this also concerns the `cmsgemos` part and in general is not currently used, but will be used later eventually with refactored version of ctp7 modules, where the corresponding changes have to be implemented.

2019-07-04 14:36 UTC, jsturdy approved these changes
cursory

2019-07-05 08:16 UTC, mexanick commented
@bdorney please see my comment considering outstanding issues

2019-07-08 08:28 UTC, bdorney commented on xhalcore/src/common/rpc_manager/daq_monitor.cc
>                  for(int vfatN = 0; vfatN < 24; ++vfatN){
Isn't this still outstanding?

2019-07-08 08:32 UTC, bdorney commented
> Still need some GE2/1 vs. GE1/1 fixes, e.g.:
> 
> * number of GBT's here:
> 
> https://github.com/mexanick/xhal/blob/58984c8cc70ffa03620a1388ce20fab7ba646da4/xhalcore/src/common/rpc_manager/daq_monitor.cc#L254-L261
> 
> * Number of VFATs here:
> 
> https://github.com/mexanick/xhal/blob/58984c8cc70ffa03620a1388ce20fab7ba646da4/xhalcore/src/common/rpc_manager/daq_monitor.cc#L263-L269
> https://github.com/mexanick/xhal/blob/58984c8cc70ffa03620a1388ce20fab7ba646da4/xhalcore/src/common/rpc_manager/daq_monitor.cc#L458-L469
> 
> * For GE2/1 this might generate key errors?
> 
> https://github.com/mexanick/xhal/blob/58984c8cc70ffa03620a1388ce20fab7ba646da4/xhalcore/src/common/rpc_manager/daq_monitor.cc#L339-L366
> 
> Aside from these issues I think you're good; the SCA one could also be a separate issue.

@mexanick In addition to this comment [here](https://github.com/cms-gem-daq-project/xhal/pull/119#discussion_r300975959) I see the above issues are still outstanding.

2019-07-08 08:32 UTC, bdorney requested changes
Still seems like some outstanding issues have not been addressed, comments [here](https://github.com/cms-gem-daq-project/xhal/pull/119#issuecomment-509131879)

2019-07-08 08:34 UTC, bdorney commented
> I've rebased. The compatibility in the daq_monitor part deserves a separate issue in my opinion, as this also concerns the `cmsgemos` part and in general is not currently used, but will be used later eventually with refactored version of ctp7 modules, where the corresponding changes have to be implemented.

The SCA function I agree is a separate issue due to HW changes between boards; but the other issues I pointed out in `daq_monitor.cc` just require using `nVFAT` or `nGBT` in for loops and should be addressed before this is merged.

2019-07-08 09:53 UTC, bdorney approved these changes

2019-07-08 10:16 UTC, merged