Adding test callers for V3 RPC calibration routines
cms-gem-daq-project/xhal pull request #12
Opened 2017-10-03 13:10 UTC by mexanick

## Description

Adding test callers for V3 RPC calibration routines
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

We need to test new RPC methods deployed with V3 electronics
## How Has This Been Tested?

Tested with Eagle60 and V3 electronics at QC lab
### Screenshots (if appropriate):

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-10-03 14:19 UTC, jsturdy requested changes

2017-10-03 14:19 UTC, jsturdy commented on python/reg_interface/test.py
> +  rpc_connect("eagle60")
This should just be made configurable now like the main `reg_interface` code, rather than leaving the hard-code in place indefinitely
If this script is specific for V3 (or a check on the firmware version isn't yet implemented) an additional flag/option could be considered for this purpose as well, though I strongly prefer that the software can figure out which version of the hardware is being communicated with and then acting accordingly.

2017-10-04 09:41 UTC, mexanick commented on python/reg_interface/test.py
> +  rpc_connect("eagle60")
yeah, this is dirty test script, which I normally only use to quick check the various functionality. 
I will implement this later, along with big refactoring of the rpc_standalone library which is growing too big)

2017-10-04 10:32 UTC, jsturdy approved these changes

2017-10-06 14:56 UTC, mexanick commented
Closing as obsolete

2017-10-06 14:56 UTC, closed without merging