Add more types to the templated RPC
cms-gem-daq-project/xhal pull request #123
Opened 2019-07-11 00:12 UTC by lpetre-ulb

## Description

This PR adds support for new types in the templated RPC methods:

* `std::array<T, N>` where `T` is an integral type
* `std::map<std::uint32_t, T>` where `T` is a serializable type
* `std::map<std::string, T>` where `T` is a serializable type
* Custom types (documentation with an example to follow)

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

This is the continuation of the the [previous PR](https://github.com/cms-gem-daq-project/xhal/pull/121) about the templated RPC methods.

## How Has This Been Tested?

It has been tested with the help of a dummy CPT7 module (reply with and/or log the method parameter(s)) and a ~10 lines C++ program on the DAQ machine.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-07-12 13:59 UTC, lmoureaux requested changes
The first two commits are almost perfect (small perf and style comments), but I don't really understand how custom types are supposed to work. Requesting more documentation ;)

2019-07-12 13:59 UTC, lmoureaux commented on xhalcore/include/xhal/rpc/common.h
> +            std::vector<std::uint32_t> keys{};
Use `keys.reserve(value.size())` to reduce the number of memory allocations.

2019-07-12 13:59 UTC, lmoureaux commented on xhalcore/include/xhal/rpc/common.h
> +                T val; this->load(val);
Style: line break after `;`

2019-07-12 13:59 UTC, lmoureaux commented on xhalcore/include/xhal/rpc/common.h
> +            std::vector<std::string> keys{};
`reserve`

2019-07-12 13:59 UTC, lmoureaux commented on xhalcore/include/xhal/rpc/common.h
> +                T val; this->load(val);
Line break

2019-07-12 13:59 UTC, lmoureaux commented on xhalcore/include/xhal/rpc/common.h
> +            const_cast<T &>(t).serialize(*this);
I'm not sure how this API could be used to serialize a type defined by a library (eg `std::valarray`). I get the impression that types not supported within `Message[De]serializer` are second-class citizens.

In any case some documentation about custom types would be welcome ;)

2019-07-12 18:12 UTC, lpetre-ulb commented on xhalcore/include/xhal/rpc/common.h
> +            std::vector<std::uint32_t> keys{};
Yes, good point. :-)

2019-07-12 18:13 UTC, lpetre-ulb commented on xhalcore/include/xhal/rpc/common.h
> +                T val; this->load(val);
I like this style when it is not possible to perform initialization at declaration. But ok, I'll change it.

2019-07-12 18:16 UTC, lpetre-ulb commented on xhalcore/include/xhal/rpc/common.h
> +            const_cast<T &>(t).serialize(*this);
Indeed types defined in a library are not currently supported. Since I really don't like the `const_casst` (if even it is safe when the API is properly used) I thought about another implementation. I'll fix that and include an example (for `std::array<T, N>`) as an example in the  documentation.

2019-07-12 21:49 UTC, lpetre-ulb commented
Support for types defined in libraries added as well as one custom type serialization example.

2019-07-13 07:13 UTC, lmoureaux requested changes
Nice improvement with the use of an external function :+1: Got two small comments.

2019-07-13 07:13 UTC, lmoureaux commented on xhalcore/include/xhal/rpc/common.h
> +     * // Simply define the serialize function in the xhal::rpc namespace with two parameters
> in the `xhal::rpc` namespace

Is it possible to leverage [ADL](https://en.cppreference.com/w/cpp/language/adl)? I think it's better than defining the function in another `namespace`, but the rules can be... confusing. (One can't use ADL for `std` classes, but it would be possible for custom ones.)

2019-07-13 07:13 UTC, lmoureaux commented on xhalcore/include/xhal/rpc/common.h
> +        for (auto & elem: value) {
Maybe add the following comment:
```cpp
// Since the size of the array is known at compile time (and part of the signature),
// we don't need to serialize it.
```

2019-07-13 10:44 UTC, lpetre-ulb commented on xhalcore/include/xhal/rpc/common.h
> +     * // Simply define the serialize function in the xhal::rpc namespace with two parameters
Yes, it is. But ADL with templates is very tricky...

If you define the `serialize` function in the same namespace as the type you want to serialize the function is found and used. (Let's wait C++20 to allow support for the `std` classes...) You can also define a file scope `serialize` function, but it must come *before* the `Message[De]serializer` classes: only ADL lookup is performed in the instantiation context. So if the types is defined in the global namespace it works.

So yes possible, but subtle. Do you want me to relax the constraints in the documentation? For e.g.
> in the xhal::rpc namespace or the namespace where the type is defined

2019-07-15 09:11 UTC, jsturdy commented on xhalcore/include/xhal/rpc/common.h
>          wisc::RPCMsg *m_wiscMsg;
Any reason this isn't a member of the base class?
Also, my usual question, does it make sense to have this a smart pointer, or are there no risks of leaks?

2019-07-15 13:40 UTC, lpetre-ulb commented on xhalcore/include/xhal/rpc/common.h
>          wisc::RPCMsg *m_wiscMsg;
> Any reason this isn't a member of the base class?

Yes, this member is `const` in the deserializer (see line 258).

> Also, my usual question, does it make sense to have this a smart pointer, or are there no risks of leaks?

Not really; this is a raw pointer given by the `rpcsvc` daemon which manages its lifetime. And when used in `xhal::rpc::call` the address of the local object is used.

2019-07-15 14:46 UTC, jsturdy approved these changes

2019-07-15 14:46 UTC, jsturdy commented on xhalcore/include/xhal/rpc/common.h
>          wisc::RPCMsg *m_wiscMsg;
> > Any reason this isn't a member of the base class?
> 
> Yes, this member is `const` in the deserializer (see line 258).

Ah, yes, I elided the `const` part there.

> 
> > Also, my usual question, does it make sense to have this a smart pointer, or are there no risks of leaks?
> 
> Not really; this is a raw pointer given by the `rpcsvc` daemon which manages its lifetime. And when used in `xhal::rpc::call` the address of the local object is used.

OK

2019-07-16 12:39 UTC, lmoureaux commented on xhalcore/include/xhal/rpc/common.h
> +     * // Simply define the serialize function in the xhal::rpc namespace with two parameters
The proposed wording is more clear. I think we should use ADL for our own types and `xhal::rpc` for everything else.

2019-07-18 12:06 UTC, jsturdy commented on xhalcore/include/xhal/rpc/common.h
> +     * // Simply define the serialize function in the xhal::rpc namespace with two parameters
@lmoureaux, is this the only thing remaining from "changes requested"?

2019-07-18 12:36 UTC, lmoureaux commented on xhalcore/include/xhal/rpc/common.h
> +        for (auto & elem: value) {
@jsturdy also this one

2019-07-22 21:14 UTC, lpetre-ulb commented
@lmoureaux's comments addressed.

2019-07-23 14:35 UTC, jsturdy approved these changes
One minor comment that can be addressed in a future PR is the style for namespaces in header files.
Here you have:
```c++
namespace xhal { namespace rpc {
/// content
}}
```
and in @lmoureaux's PR (#125) he uses:
```c++
namespace xhal::rpc::helper
/// content
}}}
```

Neither of these conform with the current style of :
```c++
namespace xhal {
  namespace rpc {
/// content
  }
}
```

I don't have a strong (enough to lay down the law) preference for either (though I will continue to use the latter in `cmsgemos`), but I do have a requirement for consistency, so if someone has a strong preference one way or the other (@mexanick, @lmoureaux, @lpetre-ulb, @bdorney), please raise it, otherwise, I will adopt the same convention as is used in our other code.

2019-07-24 21:44 UTC, lpetre-ulb commented
> One minor comment that can be addressed in a future PR is the style for namespaces in header files.

I agree that we must use a uniform style; I tried to follow the [cmsgemos CONTRIBUTING guideline](https://github.com/cms-gem-daq-project/cmsgemos/blob/develop/.github/CONTRIBUTING.md), but it is not written there. Since one or two small PRs will be required to bring the last touch I also think it can be delayed until then. 

> I don't have a strong (enough to lay down the law) preference for either (though I will continue to use the latter in `cmsgemos`), but I do have a requirement for consistency, so if someone has a strong preference one way or the other (@mexanick, @lmoureaux, @lpetre-ulb, @bdorney), please raise it, otherwise, I will adopt the same convention as is used in our other code.

My only concern with the current style is that deeply nested namespaces increase the indentation by a lot, especially if one indentation is 4 spaces.

2019-07-25 09:08 UTC, jsturdy commented
> > I don't have a strong (enough to lay down the law) preference for either (though I will continue to use the latter in `cmsgemos`), but I do have a requirement for consistency, so if someone has a strong preference one way or the other (@mexanick, @lmoureaux, @lpetre-ulb, @bdorney), please raise it, otherwise, I will adopt the same convention as is used in our other code.
> 
> My only concern with the current style is that deeply nested namespaces increase the indentation by a lot, especially if one indentation is 4 spaces.

There are those (I am not one) who mandate a style of *not* indenting namespaces..., for me indentation adds visual scope information, and as we live and code in the 21st century, I am *not* concerned with strict 80 character line limits (though the way `github` displays files with ample unused whitespace on either side of the main text, *could* be a reason to adopt some guideline...)

2019-07-25 12:16 UTC, mexanick commented
I'd support the most populated namespace identation style aka 
```cpp
namespace xhal {
  namespace rpc {
/// content
  }
}
```

2019-07-25 12:16 UTC, mexanick approved these changes

2019-07-26 12:36 UTC, merged