[refactor] structure refactored for consistent building
cms-gem-daq-project/xhal pull request #135
Opened 2019-12-21 21:02 UTC by jsturdy

## Description
This PR includes all the structural changes for simplified builds.
A subsequent PR can CI integration

### Types of changes
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context
This was added as needed for 

## How Has This Been Tested?
Compilation and packaging has been well tested
Not yet tested with live system.

2020-01-01 15:58 UTC, lmoureaux requested changes
* `make` has a strange line at the end:
    ```
    make[2]: Entering directory `/afs/cern.ch/work/l/lmoureau/GEM/test/xhal/xhal'
    make[2]: Nothing to be done for `build'.
    make[2]: Leaving directory `/afs/cern.ch/work/l/lmoureau/GEM/test/xhal/xhal'
    TO DO
    make[1]: Leaving directory `/afs/cern.ch/work/l/lmoureau/GEM/test/xhal/xhal'
    ```
    In the source `TO DO` is always related to documentation.
* `make rpm` fails with:
    ```
    /afs/cern.ch/work/l/lmoureau/GEM/test/xhal/config/ci/generate_repo.sh centos7 x86_64 /afs/cern.ch/work/l/lmoureau/GEM/test/xhal/python/reg_interface_gem/rpm /afs/cern.ch/work/l/lmoureau/GEM/test/xhal/python/reg_interface_gem/rpm/build xhal
    BRANCH_NAME is feature/refactor-structure
    REL_VERSION is unstable-PKG-1.0
    BUILD_VER is 1.0.0
    BUILD_TAG is -final.dev338
    /afs/cern.ch/work/l/lmoureau/GEM/test/xhal/config/ci/generate_repo.sh: line 43: EOS_SITE_URL: unbound variable
    make[2]: *** [_rpmharvest] Error 1
    make[2]: Leaving directory `/afs/cern.ch/work/l/lmoureau/GEM/test/xhal/python/reg_interface_gem'
    make[1]: *** [reg_interface_gem.rpm] Error 2
    make[1]: Leaving directory `/afs/cern.ch/work/l/lmoureau/GEM/test/xhal/python'
    make: *** [python.rpm] Error 2
    ```
    I want a package, not the full YUM repo.
* Pleaase use an automatic formatter like `clang-format`, this will save us from so many style-related comments in the future (pass everything through the formatter and add a CI test to check that `git diff` is clean after doing it again). If you're not satisfied with the options available in CC7 by default, check with less aged versions from `devtoolset`s.

2020-01-01 15:58 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/compat.h
>  #endif
`#endif // XHAL_COMMON_RPC_COMPAT_H`

2020-01-01 15:58 UTC, lmoureaux commented on xhal/src/client/XHALDevice.cpp
> +    throw xhal::common::utils::XHALXMLParserException(strcat("XHAL XML exception: can't find node", regName.c_str()));
This use of `strcat` leads to memory corruption. Use `std::string::operator+` instead.

2020-01-01 15:58 UTC, lmoureaux commented on xhal/src/client/XHALDevice.cpp
> +    throw xhal::common::utils::XHALXMLParserException(strcat("XHAL XML exception: can't find node", regName.c_str()));
This use of `strcat` leads to memory corruption. Use `std::string::operator+` instead.

2020-01-01 15:58 UTC, lmoureaux commented on python/reg_interface_gem/Makefile
> +PythonSources=$(wildcard core/*.py)
In modern build systems, `wildcard` is considered harmful because:

1. One doesn't notice when new files are introduced, and may fail to add them to the VCS
2. The reviewer may not notice that a file is missing
3. All tests may pass even with a missing file

So in the worst case a product may be shipped with a missing file. Please refrain from using the `wildcard` function.

2020-01-06 16:02 UTC, jsturdy commented
>  I want a package, not the full YUM repo.

darn it! i had that bug and had fixed it...

2020-01-06 16:06 UTC, jsturdy commented on xhal/src/client/XHALDevice.cpp
> +    throw xhal::common::utils::XHALXMLParserException(strcat("XHAL XML exception: can't find node", regName.c_str()));
not sure where these came from, but it wasn't introduced by me...

>     * Pleaase use an automatic formatter like `clang-format`, this will save us from so many style-related comments in the future (pass everything through the formatter and add a CI test to check that `git diff` is clean after doing it again). If you're not satisfied with the options available in CC7 by default, check with less aged versions from `devtoolset`s.

Agree (:-)), but wanted to keep that change separate from this refactor (though, I guess no better time than during a refactor, that is targeting uniformity across multiple projects)

I think I prefer to do all in one subsequent PR that adds 
* `clang-format`/`clang-tidy`
* `black`/`flake8` (for `python`)
* format/rule definitions
* formatted sources

2020-01-06 16:06 UTC, jsturdy commented
>   * Pleaase use an automatic formatter like `clang-format`, this will save us from so many style-related comments in the future (pass everything through the formatter and add a CI test to check that `git diff` is clean after doing it again). If you're not satisfied with the options available in CC7 by default, check with less aged versions from `devtoolset`s.

Agree (:-)), but wanted to keep that change separate from this refactor (though, I guess no better time than during a refactor, that is targeting uniformity across multiple projects)

I think I prefer to do all in one subsequent PR that adds 
* `clang-format`/`clang-tidy`
* `black`/`flake8` (for `python`)
* format/rule definitions
* formatted sources

2020-01-06 16:09 UTC, lmoureaux commented on xhal/src/client/XHALDevice.cpp
> +    throw xhal::common::utils::XHALXMLParserException(strcat("XHAL XML exception: can't find node", regName.c_str()));
I can let it go and open an issue instead

2020-01-06 16:09 UTC, jsturdy commented on python/reg_interface_gem/Makefile
> +PythonSources=$(wildcard core/*.py)
>   1. One doesn't notice when new files are introduced, and may fail to add them to the VCS
>   2. The reviewer may not notice that a file is missing

I don't really see this as an issue, as any sensible CI build check will catch the missing files, even if the author didn't; 3 I agree is more problematic

2020-01-06 16:21 UTC, lmoureaux commented on python/reg_interface_gem/Makefile
> +PythonSources=$(wildcard core/*.py)
Seems like I forgot the most important:

4. It's impossible to know when a file is removed, and therefore nothing will be recompiled.

2020-01-06 16:22 UTC, lmoureaux commented
> formatting

Ok for doing it in another PR.

2020-01-08 11:24 UTC, jsturdy commented
> > I want a package, not the full YUM repo.
> 
> darn it! i had that bug and had fixed it...

garrgh, **had** fixed it, and the submodule in the legacy PR *does* include the fix, but the submodule pointer in this branch wasn't updated... go figure

2020-01-08 21:53 UTC, jsturdy commented on python/reg_interface_gem/Makefile
> +PythonSources=$(wildcard core/*.py)
> Seems like I forgot the most important:
> 
>   4. It's impossible to know when a file is removed, and therefore nothing will be recompiled.

Again, I see this as (almost) the same class as 1 and 2, caught by the CI

2020-02-14 08:31 UTC, jsturdy commented
Should be superseded by #133 I think?
At least #133 contains all these commits and a few more (well fewer commits because of some reshuffling and squashing)

2020-02-14 09:41 UTC, lpetre-ulb commented
> Should be superseded by #133 I think?

Indeed!

2020-02-14 10:37 UTC, jsturdy commented
Superseded by #133

2020-02-14 10:37 UTC, closed without merging