Implement new (de)serializers for the RPC calls
cms-gem-daq-project/xhal pull request #144
Opened 2020-03-08 23:02 UTC by lpetre-ulb

## Description

This PR introduces new type (de)serializers for the templated RPC calls. In addition, an new way of creating custom split (de)serializers is added.

The new supported types are:

* `bool`
* `std::uint8_t`
* `std::uin16_t`
* `std::size_t`

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

See https://github.com/cms-gem-daq-project/xhal/issues/138; used in https://github.com/cms-gem-daq-project/ctp7_modules/pull/169.

## How Has This Been Tested?

Still WIP.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-03-10 23:03 UTC, mexanick submitted a review, later dismissed
Cursory approval with few minor comments

2020-03-10 23:03 UTC, mexanick commented on xhal/include/xhal/common/rpc/common.h
> +       * @brief (De)erializer for @c std::vector<T> where @c T is a (de)serializable type
`(De)erializer`->`(De)serializer`

2020-03-10 23:03 UTC, mexanick commented on xhal/include/xhal/common/rpc/common.h
> +       * @brief (De)serializer for the @float type
What are the use cases for floats? This is a bit dangerous and may cause issues in future... I don't see many applications besides ADC conversions which IMHO should not be done on the AMC card (or, if a `float` is really needed we can use strings and convert through them...) I would remove the `float` serialization

2020-03-10 23:07 UTC, lpetre-ulb commented on xhal/include/xhal/common/rpc/common.h
> +       * @brief (De)erializer for @c std::vector<T> where @c T is a (de)serializable type
Fixed !

2020-03-10 23:13 UTC, lpetre-ulb commented on xhal/include/xhal/common/rpc/common.h
> +       * @brief (De)serializer for the @float type
:+1: It was part of the initial request, but I'm not really convinced about the use case. The serializer is required to compile the current version of the RPC module, but IMHO, the RPC module interface should change.
If there is a truly good use, I would agree to convert to strings instead (hidden in the serializer). But, for now, everything compiles as it should. ;-)

2020-03-10 23:45 UTC, lmoureaux requested changes
In addition to some nitpicking, I'd like to see a clear test plan for `float` since it's not covered by `getVFAT3ChipIDs`.

2020-03-10 23:45 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/helper.h
> +        template <typename T, typename A>                                                \
Would it be possible to use less cryptic names for the template parameters? I would also appreciate an example in the Doxygen comment for the macro.

2020-03-10 23:45 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/helper.h
> +          static decltype(func(std::declval<TT&>(), std::declval<AA&>())) test(int);     \
Please document.

2020-03-10 23:45 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/helper.h
> +          static no test(...);                                                           \
Please document.

2020-03-10 23:45 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/common.h
> +       * @brief (De)serializer for the @float type
Maybe add a `[[deprecated]]` flag right away? I agree it's a bit weird to add deprecated functions, but it would signal that passing `float`s around is not a good idea.

2020-03-10 23:45 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/common.h
> +        std::memcpy(&tmp, &value, sizeof(std::uint32_t));
Isn't `reinterpret_cast` more appropriate here? ie `msg << *reinterpret_cast<std::uint32_t*>(&value)`

2020-03-10 23:45 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/common.h
> +        std::memcpy(&value, &tmp, sizeof(float));
`reinterpret_cast`?

2020-03-10 23:45 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/common.h
> +        // 1. Store or retrieve the vector lenth
`length`

2020-03-10 23:45 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/common.h
> +        value.resize(length); // no-op during serialization
Note that this requires the value type to be *DefaultInsertable*. I guess that we won't try to serialize anything that fancy.

2020-03-11 08:56 UTC, lpetre-ulb commented on xhal/include/xhal/common/rpc/common.h
> +       * @brief (De)serializer for the @float type
There _may_ be some good use cases, so let's wait until it is decided.

2020-03-11 08:58 UTC, lpetre-ulb commented on xhal/include/xhal/common/rpc/common.h
> +        std::memcpy(&tmp, &value, sizeof(std::uint32_t));
AFAIK, `reinterpret_cast` is subject to strict type aliasing, while `memcpy` is not. Since we compile with `-O2` or `-O3`, I preferred to use the safest method. Note that compiler will most likely completely optimize the call.

2020-03-11 09:00 UTC, lpetre-ulb commented on xhal/include/xhal/common/rpc/helper.h
> +        template <typename T, typename A>                                                \
The single letter template parameters name are rather usual naming convention and are used throughout this code base. :+1: for the usage documentation in Doxygen.

2020-03-11 09:12 UTC, lpetre-ulb commented on xhal/include/xhal/common/rpc/helper.h
> +          static no test(...);                                                           \
How can this be documented? It is a **private** template function declaration which returns the `no` type; there is not definition. Actually, this is very classical C++ template meta-programming code.

2020-03-11 09:15 UTC, lpetre-ulb commented
> In addition to some nitpicking, I'd like to see a clear test plan for `float` since it's not covered by `getVFAT3ChipIDs`.

I would have liked to write a test suite, but I have no idea how to build it... If one write the following RPC method:

``` c++
void vfat3::logFloats::operator()(const std::vector<float> &value) const
{
  for (const auto& i : value)
    LOG4CPLUS_WARN(logger, i);
}
```

and trivially calls it within the templated RPC framework: `xhal::common::rpc::call<vfat3::logFloats>(conn, std::vector<float>{3.14, 42.42});`, the log output fully matches the expectations:

```
Mar 11 08:54:51 CTP7 user.warn rpcsvc: eagle48[9449] - void vfat3::logFloats::operator()(const std::vector<float>&) const - 3.14
Mar 11 08:54:51 CTP7 user.warn rpcsvc: eagle48[9449] - void vfat3::logFloats::operator()(const std::vector<float>&) const - 42.42
```

(Notice that it also test `std::vector<T>`.)

2020-03-11 09:17 UTC, lpetre-ulb commented on xhal/include/xhal/common/rpc/common.h
> +        value.resize(length); // no-op during serialization
Good point! But I wouldn't change the (de)serializer for the reason you describe. If someone runs into the issue at some point, the (de)serializer can be improved to handle this case.

2020-03-11 09:30 UTC, jsturdy commented on xhal/include/xhal/common/rpc/common.h
> +       * @brief (De)serializer for the @float type
The historical use case for floating point values has been cases where a register is read many times and an average is computed (whether calculating a rate or mean value or other somesuch) and offloading this to the card makes sense.
One could, of course, return the necessary pieces to calculate the actual desired value elsewhere, but the semantics of that feel a bit weird.
Whether there is still a need or desire for such functionality could be reevaluated...

> If there is a truly good use, I would agree to convert to strings instead (hidden in the serializer). But, for now, everything compiles as it should. ;-)

If you already believe that to be the superior way, why not just implement it as such now?  Or is that implementation significantly more work up front?

2020-03-11 09:32 UTC, jsturdy reviewed
Looks fine modulo comment on `float` and @lmoureaux's docs requests

2020-03-11 09:47 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/common.h
> +        std::memcpy(&tmp, &value, sizeof(std::uint32_t));
ok

2020-03-11 09:56 UTC, lpetre-ulb commented on xhal/include/xhal/common/rpc/common.h
> +       * @brief (De)serializer for the @float type
> > If there is a truly good use, I would agree to convert to strings instead (hidden in the serializer). But, for now, everything compiles as it should. ;-)
> 
> If you already believe that to be the superior way, why not just implement it as such now? Or is that implementation significantly more work up front?

As long as the `float` representation is the same on all the machines (and this is IEEE 754 in the vast majority of the cases), the current implementation is fine and efficient. It would nevertheless be better to have tests about that (and also about all the other (de)serializers).

2020-03-11 09:57 UTC, lmoureaux submitted a review, later dismissed
I'm satisfied with the testing performed for `float` (and that was the main point). Nitpicking comments can be addressed later.

2020-03-11 10:09 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/common.h
> +       * @brief (De)serializer for the @float type
> It would nevertheless be better to have tests about that

Does testing for `__STDC_IEC_559__` sound like a good compromise?

2020-03-11 10:15 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/common.h
> +       * @brief (De)serializer for the @float type
Or even better [`std::numeric_limits<float>::is_iec559`](https://en.cppreference.com/w/cpp/types/numeric_limits/is_iec559)

2020-03-11 22:38 UTC, lpetre-ulb commented on xhal/include/xhal/common/rpc/common.h
> +       * @brief (De)serializer for the @float type
Using `std::numeric_limits<float>::is_iec559` to check the floating point numbers representation (not yet pushed). The use cases from @jsturdy are convincing, so that the feature is not going to be deprecated as soon as it exists. If the functionality is not used (or abused), it can be re-evaluated later on.

2020-03-11 22:52 UTC, lpetre-ulb commented
All comments should have been addressed.

2020-03-11 23:00 UTC, lmoureaux requested changes
Missing `return` statements in a few functions returning non-void if (as I understand it) the custom serialization functions do so.

2020-03-11 23:00 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/common.h
>          t.serialize(msg);
I guess you're missing a `return` here?

2020-03-11 23:00 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/common.h
> +        t.save(msg);
Same (`return`)

2020-03-11 23:00 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/common.h
> +        t.load(msg);
Same (`return`)

2020-03-11 23:00 UTC, lmoureaux commented on xhal/include/xhal/common/rpc/common.h
> +       *     // The (de)serializers can also be implemented as two splt functions
`split` :P

2020-03-11 23:06 UTC, lpetre-ulb commented on xhal/include/xhal/common/rpc/common.h
>          t.serialize(msg);
(De)serialization must return `void`, the `auto-> decltype` is only used to trigger SFINAE.

2020-03-11 23:08 UTC, lpetre-ulb commented on xhal/include/xhal/common/rpc/common.h
> +       *     // The (de)serializers can also be implemented as two splt functions
Come on... but fixed!

2020-03-11 23:10 UTC, lmoureaux approved these changes

2020-03-12 08:21 UTC, mexanick commented on xhal/include/xhal/common/rpc/common.h
> +       *     // The (de)serializers can also be implemented as two splt functions
Time to enable spellchecker in your IDE? ;)

2020-03-12 08:24 UTC, mexanick approved these changes

2020-03-12 08:25 UTC, merged

2020-03-12 09:58 UTC, lpetre-ulb commented on xhal/include/xhal/common/rpc/common.h
> +       *     // The (de)serializers can also be implemented as two splt functions
Time to copy my text editor configuration to remote machines. ;)