New Feature: ultra scan modules for v2b electronics
cms-gem-daq-project/xhal pull request #30
Opened 2017-11-06 17:42 UTC by bdorney

## Description

I have expanded the scan tools for v3 electronics to also work with v2b electronics. The modules identify at runtime what behavior should be executed.

Requires: https://github.com/cms-gem-daq-project/ctp7_modules/pull/13

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

If we are moving toward RPC/XHAL framework for CTP7 we should have the tools for both v2b and v3 electronics rather than having to move back and forth between libraries.

## How Has This Been Tested?

A complete working example is shown here:
http://cmsonline.cern.ch/cms-elog/1020178

For the v2b electronics I took a per channel threshold scan using the ipbus/uhal framework and then compared the results obtained when taking data with the rpc/xhal tools shown here. As can be seen the behavior is identical.

Additionally as shown the tools also work on v3 electronics.

### Screenshots (if appropriate):
See above elog post.

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2017-11-07 14:37 UTC, mexanick requested changes

2017-11-07 14:37 UTC, mexanick commented on README.md
> +```
I have created Wiki in the repo and I think this should go there. Please consider such update

2017-11-07 14:37 UTC, mexanick commented on src/common/rpc_manager/calibration_routines.cc
>  }
I see you have removed the printing to file, but you didn't provide any other way to transfer the results. I suggest to change the return type to `uint32_t*` and return the `result` array.

2017-11-07 15:28 UTC, bdorney commented on src/common/rpc_manager/calibration_routines.cc
>  }
I'm not sure why github is flagging this as it is already like this in the develop branch, see [lines 63-79](https://github.com/cms-gem-daq-project/xhal/blob/develop/src/common/rpc_manager/calibration_routines.cc#L63).  I think this is because I forked your develop to get the `broadcastRead/Write()` behavior and so it's thinking that this is a new change (which it is not).

Moreover the input array is supplied as a pointer as we discussed originally and this is how the data is accessible to the user.  That's how the screenshots were generated in the above elog.

2017-11-07 16:06 UTC, mexanick commented on src/common/rpc_manager/calibration_routines.cc
>  }
ah, ok. I think you can safely remove the commented lines there (63-79)

2017-11-07 16:10 UTC, bdorney commented on src/common/rpc_manager/calibration_routines.cc
>  }
Will do!

2017-11-07 16:34 UTC, bdorney commented on src/common/rpc_manager/calibration_routines.cc
>  }
Ah that's what I did originally...they are already removed! :D

2017-11-07 16:40 UTC, mexanick commented on src/common/rpc_manager/calibration_routines.cc
>  }
Great! SO please move the Read.me update to the wiki part (it also follows md syntax) and I'll sign  off.

2017-11-07 16:51 UTC, bdorney commented
Actually I want to test with a latency scan first to make sure that no changes are needed when using an external trigger source

2017-11-22 14:43 UTC, mexanick commented
@bdorney, is this a final revision of the PR?

2017-12-14 14:07 UTC, bdorney commented on README.md
> +```
I'll leave it in the `README.md` but I've added the info into a wiki page:
https://github.com/cms-gem-daq-project/xhal/wiki/Compilation-Instructions

2017-12-14 14:08 UTC, bdorney commented on src/common/rpc_manager/calibration_routines.cc
>  }
Corresponding wiki page:
https://github.com/cms-gem-daq-project/xhal/wiki/Compilation-Instructions

2017-12-14 14:09 UTC, mexanick approved these changes

2017-12-14 14:09 UTC, merged