Release preparation
cms-gem-daq-project/xhal pull request #54
Opened 2018-03-09 18:00 UTC by mexanick

Few changes in view of v3.1.0 release
## Description

**New features**:
* `rwc` method in `reg_interface.py`: read all registers containing keyword supporting wild card. *USAGE*: `rwc <KeyWord>`
* `rtest` method in `reg_interface.py`: read register certain number of times with a given interval in us. *USAGE*:` rtest <regName> <number of times> <interval>`
* 'wtest` method in `reg_interface.py`: writes 1 to a register certain number of times with a given interval in us. *USAGE*: `rtest <regName> <number of times> <interval>`

**Breaking changes**:
* RPC manager library update according to name conventions describe in [`ctp7_modules`](https://github.com/cms-gem-daq-project/ctp7_modules/issues/6). 

**Bugfixes**:
* Adjust uploads list for releasing
 
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

## How Has This Been Tested?

### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-03-10 17:58 UTC, jsturdy commented
Would it make more sense to have the write test write random data?
Suppose it depends on what this test is supposed to accomplish/probe

2018-03-11 11:45 UTC, mexanick commented
Well, I wrote it quickly to have some watchdog stability tests... I don't think it is very useful indeed, but since I already wrote it, I don't see the reason to exclude it from the PR. The choice to write 1 was made because it was developed to test a kind of write-only regs where it doesn't matter what do you write

2018-03-12 09:13 UTC, bdorney commented
> The choice to write 1 was made because it was developed to test a kind of write-only regs where it doesn't matter what do you write

In some rare cases I am not sure that writing 1 will be a valid test, e.g. imaging the case where we have some signal inversion/flip in the firmware.  Will writing 1 be valid?  What about a register whose initial value is 1?

I would propose to add the ability to write a pattern of 1's and 0's on top of current functionality, the user could specify the pattern e.g. "pattern = 0b1010101"

And then it would write it and read it back.  If this is too involved it could be tabled to a future release/new feature PR.  I am not really sure on it's overall value.  Would probably need input from @evka85 or @andrewpeck.

2018-03-12 09:15 UTC, bdorney commented on python/reg_interface/reg_interface.py
> +    def do_rwc(self, args):
For the user does this mean the `kw <X>` syntax is now to be changed to `rwc`? If so I would prefer to keep backwards compatibility to still allow:

- `readKW`
- `kw`

So that user's are not befuddled by the change (e.g. "change is transparent to the user").

2018-03-12 09:16 UTC, bdorney requested changes
Require clarification regarding backwards compatibility of `reg_interface` keywords.

2018-03-12 09:50 UTC, mexanick commented
The `readKW` and `kw` methods remain intact.

On Mar 12, 2018 10:17, Brian Dorney <notifications@github.com> wrote:

@bdorney requested changes on this pull request.

Require clarification regarding backwards compatibility of reg_interface keywords.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://github.com/cms-gem-daq-project/xhal/pull/54#pullrequestreview-102964589>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHFalrCcG1KKSjOFhVv2Yxh2aEYKdo8hks5tdjzYgaJpZM4SkpLI>.

2018-03-12 09:52 UTC, bdorney approved these changes

2018-03-12 09:53 UTC, mexanick commented
I don't think it requires attention in current release

On Mar 12, 2018 10:14, Brian Dorney <notifications@github.com> wrote:

The choice to write 1 was made because it was developed to test a kind of write-only regs where it doesn't matter what do you write

In some rare cases I am not sure that writing 1 will be a valid test, e.g. imaging the case where we have some signal inversion/flip in the firmware. Will writing 1 be valid? What about a register whose initial value is 1?

I would propose to add the ability to write a pattern of 1's and 0's on top of current functionality, the user could specify the pattern e.g. "pattern = 0b1010101"

And then it would write it and read it back. If this is too involved it could be tabled to a future release/new feature PR. I am not really sure on it's overall value. Would probably need input from @evka85<https://github.com/evka85> or @andrewpeck<https://github.com/andrewpeck>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://github.com/cms-gem-daq-project/xhal/pull/54#issuecomment-372239785>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHFalhL_h0MGttpivhoMU_-O39FcmD2Eks5tdjxBgaJpZM4SkpLI>.

2018-03-24 14:47 UTC, merged