Fix exe mode when executing on card
cms-gem-daq-project/xhal pull request #68
Opened 2018-05-11 14:41 UTC by mexanick

## Description

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Fixing exe mode to work correctly on the card
## How Has This Been Tested?

tested at eagle61
examples of usage:
Examples from host:
```
reg_interface.py -e read "GEM_AMC.GEM_SYSTEM.BOARD_ID" -n eagle61
reg_interface.py -e write "GEM_AMC.GEM_SYSTEM.BOARD_ID 0xfeed" -n eagle61
```
Examples from card:
```
reg_interface.py -e read "GEM_AMC.GEM_SYSTEM.BOARD_ID"
reg_interface.py -e write "GEM_AMC.GEM_SYSTEM.BOARD_ID 0xfeed"
```
### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-05-17 16:31 UTC, jsturdy commented on python/reg_interface/reg_interface.py
> +                      help="CTP7 hostname, default is the one used at p5", default="")
is there a reason you have set 'default=""` rather than just not having a `default`?

2018-05-17 16:51 UTC, bdorney requested changes
Add a way for the program to tell the user that the keywords from the set {`read`, `write`, etc...} must be used with the `-e` option.

2018-05-17 16:51 UTC, bdorney commented on python/reg_interface/reg_interface.py
>                        help="Function to execute once", metavar="exe", default=None)
In the usage example provided:

> reg_interface.py -e read "GEM_AMC.GEM_SYSTEM.BOARD_ID" -n eagle61
reg_interface.py -e write "GEM_AMC.GEM_SYSTEM.BOARD_ID 0xfeed" -n eagle61
Examples from card:
reg_interface.py -e read "GEM_AMC.GEM_SYSTEM.BOARD_ID"
reg_interface.py -e write "GEM_AMC.GEM_SYSTEM.BOARD_ID 0xfeed"

The keywords `read` and `write` are supplied with the `-e` option.  However the help menu does not illustrate that these keywords should be used with the `-e` option (I think this was my original problem when I was trying to use `reg_interface.py` outside of interactive mode).

Is there some way that either:

1. The help menu is updated to include a statement about the need for keywords, and what keywords are supported, and/or
2. At runtime the program checks if a keyword has been supplied with the `-e` option and if no keyword is supplied it throws an error (e.g. code `os.EX_USAGE`) along with a `print` statement illustrating what keywords are supported `I was expecting keywords from the set {'read','write', etc...}`.

2018-05-17 16:57 UTC, mexanick commented on python/reg_interface/reg_interface.py
>                        help="Function to execute once", metavar="exe", default=None)
your problem was different. I was wrong usage of quotes for arguments of the method called interactively. It was not in using "-e" or "--execute"

2018-05-17 17:00 UTC, mexanick commented on python/reg_interface/reg_interface.py
> +                      help="CTP7 hostname, default is the one used at p5", default="")
yes, there two reasons:
1). this executable mode should be available both at the card and at the host and the easy way to check is a check against whether the hostname has been provided, so the default value should be empty
2). a default doesn't really make sense as we are using the tool with various ctp7 cards

2018-05-17 17:06 UTC, mexanick commented
@bdorney I don't understand your comment. Any method can be called in exe mode...

2018-05-17 17:06 UTC, bdorney commented on python/reg_interface/reg_interface.py
>                        help="Function to execute once", metavar="exe", default=None)
My problem is as described above.  The help menu did not illustrate effectively how the `-e` option should be used.  I tried:

```
reg_interface.py --hostname="eagle60" --execute="kw GEM_AMC.OH.OH0.FPGA.CONTROL.RELEASE.VERSION"
```

Which does not work.  And the help menu does *not* give enough information to deduce the syntax on the usage here:

```
% reg_interface.py -h
Usage: reg_interface.py [options]

Options:
  -h, --help            show this help message and exit
  -e exe, --execute=exe
                        Function to execute once
  -n HOSTNAME, --hostname=HOSTNAME
                        CTP7 hostname, default is the one used at p5
```

Nor does the program throw an exception which accurately explains the cause of the problem (bad syntax):

```
% reg_interface.py --hostname="eagle60" --execute "kw GEM_AMC.OH.OH0.FPGA.CONTROL.RELEASE.VERSION"
Extended prompt module found
Open pickled address table if available  Traceback (most recent call last):
  File 
xhal/python/reg_interface/reg_interface.py", line 27, in <module>
    prompt.execute(options.exe,args)
  File 
xhal/python/reg_interface/ri_prompt_extended.py", line 19, in execute
    call_func = getattr(Prompt,other_function)
AttributeError: class Prompt has no attribute 'do_kw GEM_AMC.OH.OH0.FPGA.CONTROL.RELEASE.VERSION'
```

From the help menu it is not clear that the keyword should be placed outside of quotation marks as shown in the usage example, not does the exception illustrate that either.

This should be addressed.

2018-05-17 17:07 UTC, bdorney commented on python/reg_interface/reg_interface.py
>                        help="Function to execute once", metavar="exe", default=None)
Obviously from the usage example in this PR the correct syntax is:

```
% reg_interface.py --hostname="eagle60" --execute kw "GEM_AMC.OH.OH0.FPGA.CONTROL.RELEASE.VERSION"
Extended prompt module found
Open pickled address table if available xhal/etc/gem_amc_top.pickle...
0x6500000c None 	GEM_AMC.OH.OH0.FPGA.CONTROL.RELEASE.VERSION		
0x65000014 r 	GEM_AMC.OH.OH0.FPGA.CONTROL.RELEASE.VERSION.MAJOR	0x00000003
0x65000014 r 	GEM_AMC.OH.OH0.FPGA.CONTROL.RELEASE.VERSION.MINOR	0x00000001
0x65000014 r 	GEM_AMC.OH.OH0.FPGA.CONTROL.RELEASE.VERSION.BUILD	0x00000001
0x65000014 r 	GEM_AMC.OH.OH0.FPGA.CONTROL.RELEASE.VERSION.GENERATION	0x0000000b
```

2018-05-17 17:08 UTC, bdorney commented
> @bdorney I don't understand your comment. Any method can be called in exe mode...

The comment is that from the help menu of `reg_interface.py` the syntax expected when using the `-e` option is not illustrated.  Additionally if incorrect syntax is given the output text does not given information to adequately understand the root of the problem.

2018-05-17 17:10 UTC, mexanick commented
this is fixed in last commit, please see above

2018-05-17 17:12 UTC, bdorney commented
Missed the updated commit, excellent.  This is exactly what I was hoping for!

2018-05-17 17:12 UTC, bdorney approved these changes

2018-05-17 17:13 UTC, bdorney commented on python/reg_interface/reg_interface.py
> +                      help="CTP7 hostname, default is the one used at p5", default="")
Could default it to `None` in this case.

Then local mode is understood if `hostname` is `None`.

As you wish.

2018-05-18 07:12 UTC, merged

2018-05-18 13:52 UTC, jsturdy commented on python/reg_interface/reg_interface.py
> +                      help="CTP7 hostname, default is the one used at p5", default="")
If a `default` is not provided, the option when parsed **will** be `None`