Packaging tools for x86
cms-gem-daq-project/xhal pull request #72
Opened 2018-06-13 13:00 UTC by mexanick

x86 packaging is done. After running `make rpm` two packages are created:

- `gem_reg_interface_extras-1.0.0-centos7.python2.7.x86_64.rpm`
- `xhal-xhalcore-1.0.0-centos7.x86_64.rpm`

## Description

These packages require `wiscrpcsvc`, `log4cplus` and `xercesc` (`xdaq` versions of latter two), `reg_interface-1.0.0-centos7.python2.7.x86_64.rpm`
Default installation is /opt/xhalcore/:

```bash
tree /opt/xhalcore/
/opt/xhalcore/
├── bin
│   └── gem_reg.py
├── include
├── lib
│   ├── librpcman.so
│   └── libxhal.so
└── scripts
```

Required env settings:
`LD_LIBRARY_PATH` should contain path to `libwiscrpcsvc.so` and `xhalcore/lib`
`GEM_ADDRESS_TABLE_PATH` should point to address table XML location. Address table file name should be `amc_address_table_top.xml`

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Proper packaging is required for seamless GEM operations 
## How Has This Been Tested?

Tested at `gem904daq01` with `eagle34` and `eagle64`
### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-06-13 13:02 UTC, bdorney commented
Naive question, what about an `slc6` rpm?  Or is this not going to be supported?

2018-06-13 13:07 UTC, bdorney commented on python/ctp7/dacScan.py
> -"""
Is this script being included somewhere else?  Seems like a useful tool that should not be permanently deleted.

2018-06-13 13:10 UTC, bdorney commented on python/extras/makeDACtree.py
> -myF.Close()
seems related to [this](https://github.com/cms-gem-daq-project/xhal/pull/72/files#r195073305) comment

2018-06-13 13:13 UTC, bdorney commented on python/reg_interface/gbt.py
> -    programGBT(ohSelect, gbtSelect, command)
This is a necessary script, especially for programming `GBTx`'s over the fiber link.  If it is being deleted I trust it's  being included elsewhere, if so where?

2018-06-13 13:13 UTC, bdorney commented on python/reg_interface/mcs.py
> -    main()
Again, where is this script being moved too?

2018-06-13 13:14 UTC, bdorney commented on python/reg_interface/rw_reg.py
> -    main()
Right now this is necessary for all `v3` actions.  Where will this file be found at in the future? e.g. what is the proper import.

2018-06-13 13:15 UTC, bdorney commented on python/reg_interface/test.py
> -  print "Total time %s" %(elapsed)
same comment, where is this getting moved too?

2018-06-13 13:16 UTC, bdorney requested changes
Clarification requested on several scripts being deleted from the repo and request to change `amc_address_table_top.xml` to something that sync's better with `cmsgemos`.

2018-06-13 16:30 UTC, jsturdy commented
@bdorney `reg_interface` "basic" and friends are now in [`reg_utils`](https://github.com/cms-gem-daq-project/reg_utils/tree/master/python/reg_interface), with the "GEM specific" extensions provided by `xhal`

> This seems to conflict with what setupMachine.sh from cmsgemos is doing:

`setupMachine.sh` doesn't do anything related to package structure, this is taken care of by the machine profile RPM, e.g., `cmsgemos-gem904qc8` (currently incomplete).  Though it currently lives in `cmsgemos` it will migrate to the "meta" package repository to properly include all external inputs (`GEM_AMC` generated address tables, TCDS configurations, setup specific patches to certain `python` files, etc.) as needed (whether through a script, or as an RPM installing a fixed "meta" release).  Currently installing the machine profile will create the structure, and provide a few setup specific files, but the address tables are currently updated manually.

2018-06-13 16:39 UTC, jsturdy reviewed
Not sure I understand the `xhalcore` division, is it a placeholder for something future?

2018-06-14 07:21 UTC, mexanick commented on python/reg_interface/gbt.py
> -    programGBT(ohSelect, gbtSelect, command)
it is for the moment under `reg_utils`. Maybe we will move it back to gem-specific extension. I'm still waiting inputs from @evka85

2018-06-14 07:22 UTC, mexanick commented on python/ctp7/dacScan.py
> -"""
No, it is missing. I thought it was migrated under `gempython` - is it not?

2018-06-14 07:23 UTC, mexanick commented on python/reg_interface/mcs.py
> -    main()
Again, it is under `reg_utils`

2018-06-14 07:27 UTC, jsturdy commented on python/ctp7/dacScan.py
> -"""
it's in a private branch (was not intended for public consumption even when i gave it to you :-) )

2018-06-14 07:30 UTC, mexanick commented on python/reg_interface/rw_reg.py
> -    main()
It depend on what you want to import. The functionality is divided in a following way:
`reg_utils.reg_interface.common.reg_xml_parser` takes care about XML parsing-related business like `parseXML` method and contains `Node` class definition
`reg_utils.reg_interface.common.reg_base_ops` loads a very basic `librwreg.so` 
`xhal.gem_reg_interface_extras.core.reg_extra_ops` provides access to `librpcman.so` functions

2018-06-14 07:30 UTC, mexanick commented on python/reg_interface/test.py
> -  print "Total time %s" %(elapsed)
for the moment nowhere. Will be added later

2018-06-14 07:33 UTC, mexanick commented
Certain headers may be added later under `xhalcore/include`. Testing will be added eventually under scripts. What else is unclear?

2018-06-14 07:35 UTC, mexanick commented
Considering the address table: for the moment `setupMachine` seems to not care about address tables supplied by @evka85 and @andrewpeck at all. I would prefer to have a generic name there because the XML parser is a part of generic, non gem-specific `reg_utils/reg_interface` package

2018-06-14 09:20 UTC, jsturdy commented
> Certain headers may be added later under xhalcore/include. Testing will be added eventually under scripts. What else is unclear?

I guess my question was more, why is the package called `xhalcore` rather than `xhal`?
Installed into a location `/opt/xhal`, and if sub packages exist at some point, then package them as `xhal-<subpackage>`, e.g., `xhal-core`

2018-06-14 11:22 UTC, mexanick commented
ah, that's because of some name conventions and makefiles... I can try to revisit it if you insist

2018-06-14 12:15 UTC, jsturdy commented
I have a moderate preference for revisiting :-), as I find the `xhalcore` awkward

2018-06-18 14:59 UTC, mexanick commented
namespace changed to `xhal`
@bdorney anything you still want to change? If so, please elaborate :)

2018-06-19 13:08 UTC, bdorney commented on python/reg_interface/gbt.py
> -    programGBT(ohSelect, gbtSelect, command)
Okay so we are just moving the location, not removing it.  Got it.

2018-06-19 13:08 UTC, bdorney commented on python/reg_interface/mcs.py
> -    main()
Understood.

2018-06-19 13:10 UTC, bdorney commented on python/reg_interface/rw_reg.py
> -    main()
Okay I understood.  So some adding of multiple imports will resolve any dependency.

2018-06-19 13:12 UTC, bdorney commented
Okay so it seems my concerns are just my own ignorance!  I'll need to consult the updated documentation for `xhal` and `reg_utils`.

2018-06-19 13:13 UTC, bdorney approved these changes

2018-06-19 14:55 UTC, merged