Adding XHALInterface constructor accepting external logger
cms-gem-daq-project/xhal pull request #91
Opened 2018-09-12 13:55 UTC by mexanick

## Description

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

## How Has This Been Tested?

### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-09-18 12:59 UTC, jsturdy commented
Is this waiting on anything?

2018-09-18 13:02 UTC, mexanick commented
on your, @jsturdy and @bdorney reviews =)

2018-09-18 13:02 UTC, jsturdy commented on xhalcore/Makefile
> +	-${RM} ${XHALCORE_LIB} ${XHALPY_LIB} ${OBJS_UTILS} ${OBJS_XHAL} ${RPC_MAN_LIB} ${OBJS_RPC_MAN} ${OBJS_XHALPY}
why `$(RM) when `-rm` is used the next line?

2018-09-18 13:24 UTC, mexanick commented on xhalcore/Makefile
> +	-${RM} ${XHALCORE_LIB} ${XHALPY_LIB} ${OBJS_UTILS} ${OBJS_XHAL} ${RPC_MAN_LIB} ${OBJS_RPC_MAN} ${OBJS_XHALPY}
Historic reasons... Can go with any (and `${RM}` states for `rm -f` by default`) 
Let me know if you have strong preference

2018-09-18 21:31 UTC, jsturdy commented on xhalcore/Makefile
> +	-${RM} ${XHALCORE_LIB} ${XHALPY_LIB} ${OBJS_UTILS} ${OBJS_XHAL} ${RPC_MAN_LIB} ${OBJS_RPC_MAN} ${OBJS_XHALPY}
My preference is always consistency and uniformity when there isn't a reason for a difference :-)

2018-09-28 10:10 UTC, bdorney commented on xhalcore/include/xhal/XHALInterface.h
> +#define XHAL_FATAL(MSG) LOG4CPLUS_FATAL(m_logger, MSG)
All of these errors below are catching on something from `wish::RPCSvc`.  Is there any reason why we are providing this wrapper?  e.g. why not call these all `RPC_TRACE`, ..., `RPC_WARN`, ..., etc...?

2018-09-28 10:12 UTC, bdorney commented
Since #89 has been blocked, and we have a reconnect method, can you incorporate `loadStoredModules()` from:

https://github.com/cms-gem-daq-project/xhal/pull/89/files#diff-a547ad5e911c04f37c34a25a514b49b5

To this PR?  And then have it called by both `connect` and `reconnect` as shown in the above PR.  This alleviated some issues I was having when using the exposed bindings in python.

2018-09-28 10:14 UTC, bdorney commented on xhalcore/include/xhal/utils/XHALXMLParser.h
> +#define XHAL_FATAL(MSG) LOG4CPLUS_FATAL(m_logger, MSG)
Ignorant question, but why do these have to be defined in two different locations instead of just being loaded from a header file in both cases?  E.g. they are defined here in `XHALXMLParser.h` and also above in `XHALInterface.h`

2018-09-28 10:16 UTC, bdorney commented on xhalcore/src/common/XHALInterface.cpp
> +xhal::XHALInterface::XHALInterface(const std::string& board_domain_name, log4cplus::Logger& logger):
Maybe I missed a commit somewhere, but wasn't the constructor here at least loading the baseline rpc modules? e.g. `memory.so`?

What is our plan for loading modules, does this happen in the cmsgemos class or here?

2018-09-28 10:19 UTC, bdorney requested changes
Some clarifications needed.

2018-09-28 10:20 UTC, mexanick commented on xhalcore/include/xhal/XHALInterface.h
> +#define XHAL_FATAL(MSG) LOG4CPLUS_FATAL(m_logger, MSG)
there could be errors not associated with the RPC itself, which also has to be catched and transmitted correctly

2018-09-28 10:21 UTC, mexanick commented
> Since #89 has been blocked, and we have a reconnect method, can you incorporate `loadStoredModules()` from:
> 
> https://github.com/cms-gem-daq-project/xhal/pull/89/files#diff-a547ad5e911c04f37c34a25a514b49b5
> 
> To this PR? And then have it called by both `connect` and `reconnect` as shown in the above PR. This alleviated some issues I was having when using the exposed bindings in python.

No. It is not related to the scope of current PR.

2018-09-28 10:22 UTC, mexanick commented on xhalcore/src/common/XHALInterface.cpp
> +xhal::XHALInterface::XHALInterface(const std::string& board_domain_name, log4cplus::Logger& logger):
No, it provides an interface and is a base class. Loading modules should be (and is) implemented in descendant classes, e.g. XHALDevice

2018-09-28 10:23 UTC, mexanick commented on xhalcore/include/xhal/utils/XHALXMLParser.h
> +#define XHAL_FATAL(MSG) LOG4CPLUS_FATAL(m_logger, MSG)
Will be refactored in future. There're more deep issues with logging, which may require more work

2018-09-28 15:57 UTC, bdorney commented on xhalcore/include/xhal/XHALInterface.h
> +#define XHAL_FATAL(MSG) LOG4CPLUS_FATAL(m_logger, MSG)
For sure I don't disagree with that statement, but it seems the implementation of these below is based solely on `wisc::RPCSvc::*Exception` objects.  In my mind an `xhal` exception/error/statement should be xhal specific and the below should be `RPC` specific e.g.:

 ```C++
#define RPC_TRACE(MSG) LOG4CPLUS_TRACE(m_logger, MSG)
#define RPC_DEBUG(MSG) LOG4CPLUS_DEBUG(m_logger, MSG)
#define  RPC_INFO(MSG) LOG4CPLUS_INFO(m_logger, MSG)
#define RPC_WARN(MSG) LOG4CPLUS_WARN(m_logger, MSG)
#define RPC_ERROR(MSG) LOG4CPLUS_ERROR(m_logger, MSG)
#define RPC_FATAL(MSG) LOG4CPLUS_FATAL(m_logger, MSG)

#define XHAL_TRACE(MSG) LOG4CPLUS_TRACE(m_logger, MSG)
#define XHAL_DEBUG(MSG) LOG4CPLUS_DEBUG(m_logger, MSG)
#define XHAL_INFO(MSG) LOG4CPLUS_INFO(m_logger, MSG)
#define XHAL_WARN(MSG) LOG4CPLUS_WARN(m_logger, MSG)
#define XHAL_ERROR(MSG) LOG4CPLUS_ERROR(m_logger, MSG)
#define XHAL_FATAL(MSG) LOG4CPLUS_FATAL(m_logger, MSG)
```

Where first set is the below and the second is XHAL specific...or maybe it's my ignorance and I have misunderstood the use case/intention.

2018-09-28 15:58 UTC, bdorney commented on xhalcore/include/xhal/utils/XHALXMLParser.h
> +#define XHAL_FATAL(MSG) LOG4CPLUS_FATAL(m_logger, MSG)
Okay.

2018-09-28 15:58 UTC, bdorney commented on xhalcore/src/common/XHALInterface.cpp
> +xhal::XHALInterface::XHALInterface(const std::string& board_domain_name, log4cplus::Logger& logger):
Okay.

2018-09-28 15:58 UTC, bdorney commented
> No. It is not related to the scope of current PR.

Fair enough but I think it would be good to have this in a future PR.

2018-10-01 06:49 UTC, mexanick commented on xhalcore/include/xhal/XHALInterface.h
> +#define XHAL_FATAL(MSG) LOG4CPLUS_FATAL(m_logger, MSG)
I'm afraid you are mixing the logging with exception handling. The exceptions translation is done differently and reflects an origin of it. This, instead, is only logging macros.

2018-10-01 08:14 UTC, bdorney approved these changes

2018-10-01 08:18 UTC, merged