[WIP] New Feature: Added legacy xhal routine for DAC scans of VFAT3 (PreBoost)
cms-gem-daq-project/xhal pull request #93
Opened 2018-09-28 08:17 UTC by bdorney

## Description

WIP

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

## How Has This Been Tested?

### Screenshots (if appropriate):

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-10-09 07:55 UTC, mexanick commented on xhalcore/include/xhal/rpc/calibration_routines.h
> +        //I wonder if this dacMin and dacMax info could be added to the LMDB...?
I'm against adding this info in an address table representation in LMDB because I want to keep it as light as possible. However, if there's a strong concern, we may add second LMDB which will keep only these values...

2018-10-09 07:55 UTC, mexanick commented on xhalcore/src/common/rpc_manager/calibration_routines.cc
> +    const uint32_t size = NOH * (dacSize.max[dacSelect] - 0+1)*24/dacStep;
I don't understand this `dacSize.max[dacSelect] - 0+1`... typo?

2018-10-09 07:57 UTC, bdorney commented on xhalcore/src/common/rpc_manager/calibration_routines.cc
> +    const uint32_t size = NOH * (dacSize.max[dacSelect] - 0+1)*24/dacStep;
it was a placeholder to remind myself that the size should be:

24 * (max - min + 1) / step

Where min was always 0.

2018-10-10 14:41 UTC, mexanick requested changes
the placeholder "-0 +1" must be removed

2018-10-10 14:43 UTC, mexanick commented on xhalcore/include/xhal/rpc/calibration_routines.h
> +        //I wonder if this dacMin and dacMax info could be added to the LMDB...?
all this hardcoded info will make complicated future maintenance. Please consider other ways of retrieving it

2018-10-10 15:02 UTC, bdorney commented on xhalcore/include/xhal/rpc/calibration_routines.h
> +        //I wonder if this dacMin and dacMax info could be added to the LMDB...?
I thought the goal was that we wouldn't be maintaining this in the future; isn't this branch being depreciated after the updates to the HwDevice in cmsgemos?  Anyway that's secondary.

The key point would be that this is designed to solve a problem that won't exist in the future, namely we are forced to work with pointers to c-arrays with fixed size because the python API can't access this info otherwise.

In the future this method would be in cmsgemos, be returning from the `RPCMsg` a vector instead of writing to an array pointer.  And then that would be exposed to a python list or some other dynamic sized container.

In short `struct vfat3DACSize` won't exist in the future.  This will then be purely handled by the scan application.

2018-10-10 15:03 UTC, bdorney commented on xhalcore/include/xhal/rpc/calibration_routines.h
> +        //I wonder if this dacMin and dacMax info could be added to the LMDB...?
Unless we modify the address table (either xml or lmdb) to include the max size of a register I'm not sure what else could be done.  Is that what is being requested?

2018-10-10 15:04 UTC, bdorney commented
> the placeholder "-0 +1" must be removed

The `-0` I can remove, but the `+1` is required to get the index correct. :D

2018-10-12 10:10 UTC, mexanick submitted a review, later dismissed

2018-10-17 07:40 UTC, bdorney commented
@mexanick @jsturdy @BenjaminRS I had to add one last commit (ed9a23e) per VFAT3 team's instructions.  We should not scan `CFG_IREF` with the VFAT3's internal ADC's since this can only be scanned with an external ADC.

Additionally the VFAT3 Team mentioned that writing a value to `CFG_IREF` below `0x20` or above `0x32` may cause damage to the ASIC.

Review needed again.

2018-10-18 14:50 UTC, mexanick approved these changes

2018-10-24 14:09 UTC, jsturdy approved these changes

2018-10-24 14:14 UTC, BenjaminRS approved these changes

2018-11-07 16:34 UTC, merged